language: ruby

before_install:
  - gem install bundler -v ${BUNDLER_VERSION}
  - cd source
  - sed -i -e "s/\(gem 'vagrant'.*tag. \)'[^']*'\(.*\)/\1'${VAGRANT_VERSION}'\2/" Gemfile

install:
  - travis_retry bundle _${BUNDLER_VERSION}_ install --without debug

script:
  - bundle _${BUNDLER_VERSION}_ exec rake

matrix:
  include:
    - rvm: 2.0.0
      env: VAGRANT_VERSION=v1.6.5 BUNDLER_VERSION=1.6.6
    - rvm: 2.0.0
      env: VAGRANT_VERSION=v1.7.4 BUNDLER_VERSION=1.10.5

    - rvm: 2.2.3
      env: VAGRANT_VERSION=v1.8.1 BUNDLER_VERSION=1.10.6

sudo: false
