language: ruby

before_install:
  - cd source
  - sed -i -e "s/\(gem 'vagrant'.*tag. \)'[^']*'\(.*\)/\1'${VAGRANT_VERSION}'\2/" Gemfile

install:
  - travis_retry bundle install --without debug

script:
  - bundle exec rake

matrix:
  include:
    - rvm: 2.2.5
      env: VAGRANT_VERSION=v1.9.8
    - rvm: 2.2.5
      env: VAGRANT_VERSION=v2.0.2

sudo: false
