language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

before_install:
  - cd source

install:
  - "travis_retry bundle install"
  - "travis_retry appraisal install"

script: "appraisal rake"

gemfile:
  - Gemfile
  - gemfiles/latest_stable.gemfile
  - gemfiles/oldest_current.gemfile
  - gemfiles/previous_release.gemfile
